### ISSUE TITLE
predicate stops at false result?

### ISSUE THREAD

**Issue by yongheekim-dev** [JuliaIO/Tar.jl#28]
I have directory tree like this 
```
MyData
ㄴ Child 
     ㄴ a.txt
ㄴ b.txt
ㄴ c.git
```

And predicate do not walk through child directory as I expected 
``` julia
# wraps all files to .tar under "MyData"
predicate = path -> (println(path); true)
Tar.create(predicate , "MyData", "out.tar")
#= this prints out
 MyData/b.txt
 MyData/c.git
 MyData/Child/a.txt
=#

# Child/a,txt in not included on .tar
predicate = path -> (println(path); endswith(path,"txt"))
Tar.create(predicate, "MyData", "out.tar")
#= this prints out
 MyData/b.txt
 MyData/c.git
=#
```

I'm on Windows10
```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by StefanKarpinski** [comment]
This is behaving as intended although perhaps the documentation should be more explicit about this. If an archive included anything under the `Child` directory, then it contains the `Child` directory. So if `Child` is rejected by the predicate, the archive cannot contain anything under `Child`. You can do something closer to what you want by making the predicate `isdir(path) || splitext(path)[2] == "txt"` although that would include empty directories that don't have any `txt` files in them, which you may not want. It might be good to add an option to skip directories that don't contain any files in them.

**Comment by StefanKarpinski** [comment]
I looked at adding an option to `Tar.create` that skips directory subtrees that don't end up including any non-directories, but unlike the relatively simple question of whether `predicate` is true for any of the current directory's immediate children, that inherently requires recursion in advance, at which point you may as well create your list of files to include before the `Tar.create` call by whatever means you prefer (e.g. by using `walkdir` or the `find` command). Then, given a list of paths that _must_ be included, you want to convert that into a predicate that is true for any of those paths and any of the directories that need to be included in order to include all of them. You can think of this as taking the closure of the set of paths under `dirname`—and a first cut implementation did just that.

However, this is complicated by the fact that there are countless variations on how to express each path and if we're going to make a proper API for making a tarball that includes everything needed to archive a given list of paths, then we need to handle all those variations in ways that paths can be written. One possible solution to that is to call `stat` on paths and use `samefile` to compare them, but `stat` is slow and expensive, so we want to avoid that if at all possible. A different approach is to normalize paths as a pure string computation to eliminate variation in how they are expressed. This normalization involves a lot of string splitting and joining, which looks expensive, but is probably (I haven't benchmarked) much cheaper than hitting the file system to stat everything. Here's a cut at the path normalization approach:
```jl
function path_list_predicate(dir::AbstractString, paths::AbstractVector{<:AbstractString})
    prefixes = String[]
    for path in paths
        path = relpath(normpath(path), dir)
        parts = splitpath(path)
        !isempty(parts) && parts[1] == ".." &&
            throw(ArgumentError("path $(repr(path)) is outside of tarball root $(repr(dir))"))
        path = joinpath(parts...)
        while path ∉ prefixes
             push!(prefixes, path)
             path = dirname(path)
        end
    end
    path -> relpath(normpath(path), dir) in prefixes
end
```
Here this is in action:
```jl
julia> tarball = Tar.create(path_list_predicate(".", readlines(`find /Users/stefan/dev/Tar -type f -name '*.jl'`)), ".")
"/var/folders/4g/b8p546px3nd550b3k288mhp80000gp/T/jl_b0k9iW"

julia> Tar.list(tarball)
5-element Array{Tar.Header,1}:
 Tar.Header("src/Tar.jl", :file, 0o644, 5193, "")
 Tar.Header("src/create.jl", :file, 0o644, 7723, "")
 Tar.Header("src/extract.jl", :file, 0o644, 9403, "")
 Tar.Header("src/header.jl", :file, 0o644, 3722, "")
 Tar.Header("test/runtests.jl", :file, 0o644, 14216, "")
```
It's tempting to add this functionality, but it's not entirely complete since you'd presumably also want to verify at the end that you actually did include every path listed and none of them were missed.

**Comment by yongheekim-dev** [comment]
Thank you for clarification and detailed reasoning. 
I'm not skilled at linux `tar` commands. But I think the functionality of `Tar.jl` resembles linux tar commands would make Tar.jl more simple and maintainable

So adding functions like `path_list_predicate`  doesn't seem to necessary. adding usage of predicate with `isdir(path) || splitext(path)[2]` on `Tip&Trickes` of document would be nice solution on this matter. 

Thank you again for taking your time to explain this
